### ISSUE TITLE
事件流程树中键鼠模拟修改数据弹窗显示不完整

### ISSUE THREAD

**Issue by shenghuadun** [edgehacker/live-tool#1]
![1708844307687](https://github.com/edgehacker/live-helper/assets/4532852/fd4f42f4-f2a7-4074-a5ea-0f790f5a4af1)

**Comment by edgehacker** [comment]
> ![1708844307687](https://private-user-images.githubusercontent.com/4532852/307572716-fd4f42f4-f2a7-4074-a5ea-0f790f5a4af1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjgyMTEsIm5iZiI6MTcwODg2NzkxMSwicGF0aCI6Ii80NTMyODUyLzMwNzU3MjcxNi1mZDRmNDJmNC1mMmE3LTQwNzQtYTVlYS0wZjc5MGY1YTRhZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTMzMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA3M2NlMWM3MmZlMTlhNmY1OTM0NTIyY2Q4YzMzYzRhYTlhYmY0NmViMWIwYWExNGRhY2NlZTA5MWQ4YzVhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6qd36IZNOVd4sqeyLbZmOhp8ZLs72FPksBoKWCGkTq0)

请提供系统版本及屏幕分辨率，以便我们进一步测试

**Comment by shenghuadun** [comment]
Windows 10 专业版 22H2 19045.4046
分辨率为3440*1440，缩放试了125%和100%都一样显示不全

**Comment by edgehacker** [comment]
> Windows 10 专业版 22H2 19045.4046 分辨率为3440*1440，缩放试了125%和100%都一样显示不全

您好，我们这边安排技术员远程为您排查问题，请加入QQ群聊829242770，联系管理员"清雨"远程排查问题
